"""Python port of the fundamental-screener Strength/Risk scorer, v5.

Line-for-line faithful to ``fundamental-screener@0fa9049 lib/scoring.ts``
(SCORING_VERSION = 5) plus ``clampFraction`` from ``lib/range.ts``. The parity
test ``tests/test_scoring_v5.py`` replays the golden fixtures generated by the
TypeScript scorer (``tests/fixtures/scoring-v5-golden.json``) and requires
exactly identical output -- that is the QR-008 "frozen as-is" guarantee.

Rows are mappings with the ScanRow camelCase keys (``trailingPE``,
``fcfYieldPercent``, ...). Percent-valued inputs are percents, exactly as the
screener receives them; the QC field-mapping layer (fraction -> x100,
non-positive ratios -> None, the non-payer dividend rule, derived 5Y margin)
belongs to the QR-008 experiment adapter, not here.

Do not "fix" or tune anything in this file: any behavior change must happen in
the TypeScript scorer first, bump SCORING_VERSION, and regenerate the fixtures.
"""

from __future__ import annotations

import math
import re
from collections.abc import Mapping
from typing import Any

SCORING_VERSION = 5

MAX_STRENGTH = 21
MAX_RISK = 20
RISK_FLOOR = 8

MEGA_CAP_THRESHOLD = 200_000_000_000
EXTREME_DE_RATIO = 10
WEAK_INTEREST_COVERAGE = 2
STRONG_INTEREST_COVERAGE = 6

SUSPECT_REV_GROWTH_FINANCIAL = 60
SUSPECT_REV_GROWTH_GENERAL = 300

EQ_CONVERSION_STRONG = 1.0
EQ_CONVERSION_WEAK = 0.7
EQ_CONVERSION_CRITICAL = 0.5
BENIGN_EQ_MIN_FCF_YIELD = 2
BENIGN_EQ_MIN_REV_GROWTH = 20

REV_ACCEL_THRESHOLD_PP = 3
MARGIN_INFLECTION_PP = 1

MIN_CRITERION_COVERAGE = 0.7
TRAP_CHEAP_EV_EBITDA = 8
TRAP_CHEAP_FCF_YIELD = 8

# JS Number.MIN_VALUE / Number.MAX_VALUE (sanitize bounds use them as
# "strictly positive" / "any finite" limits).
_JS_MIN_VALUE = 5e-324
_JS_MAX_VALUE = 1.7976931348623157e308

CRITERION_KEYS = [
    "earningsQuality",
    "leverage",
    "revenueGrowth",
    "revenueAcceleration",
    "fcfYieldLevel",
    "marginInflection",
    "peCompression",
    "valuation",
    "dividendCoverage",
    "pricePosition",
    "ytdMomentum",
    "dividendYield",
]

CRITERION_WEIGHT = {
    "earningsQuality": 3,
    "leverage": 3,
    "revenueGrowth": 2,
    "revenueAcceleration": 2,
    "fcfYieldLevel": 2,
    "marginInflection": 2,
    "peCompression": 2,
    "valuation": 1,
    "dividendCoverage": 1,
    "pricePosition": 1,
    "ytdMomentum": 1,
    "dividendYield": 1,
}

_CYCLICAL_PATTERNS = [
    r"semiconductor",
    r"automobile", r"\bautos?\b", r"auto components",
    r"\boil\b", r"\bgas\b", r"\bcoal\b", r"petroleum", r"drilling",
    r"energy equipment", r"consumable fuels",
    r"mining", r"metals", r"\bsteel\b", r"aluminum",
    r"chemical",
    r"\bmarine\b", r"shipping",
    r"airline",
    r"construction", r"building", r"homebuild",
    r"paper", r"forest",
]
_FINANCIAL_PATTERNS = [r"financ", r"\bbank", r"insurance", r"capital markets"]
_REIT_PATTERNS = [r"\breits?\b", r"real estate"]

_OVERRIDE_BALANCE_SHEET = {"COF", "DFS", "AXP", "SYF", "ALLY"}
_OVERRIDE_ASSET_LIGHT = {
    "BLK", "TROW", "BEN",
    "CME", "ICE", "NDAQ", "CBOE",
    "SPGI", "MCO", "MSCI", "FDS", "MORN",
    "V", "MA",
}


def _matches(industry: Any, patterns: list[str]) -> bool:
    return isinstance(industry, str) and any(
        re.search(p, industry, re.IGNORECASE) for p in patterns
    )


def is_cyclical_industry(industry: Any) -> bool:
    return _matches(industry, _CYCLICAL_PATTERNS)


def is_financial_industry(industry: Any) -> bool:
    return _matches(industry, _FINANCIAL_PATTERNS)


def is_reit_industry(industry: Any) -> bool:
    return _matches(industry, _REIT_PATTERNS)


def classify_financial_model(ticker: Any, industry: Any) -> str:
    t = (ticker or "").strip().upper() if isinstance(ticker, str) else ""
    if t in _OVERRIDE_BALANCE_SHEET:
        return "balance-sheet"
    if t in _OVERRIDE_ASSET_LIGHT:
        return "asset-light"
    return "balance-sheet" if is_financial_industry(industry) else "non-financial"


def is_balance_sheet_financial(ticker: Any, industry: Any) -> bool:
    return classify_financial_model(ticker, industry) == "balance-sheet"


def _n(value: Any) -> float | int | None:
    """Finite number else None (mirrors the TS n(); booleans excluded)."""
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        return None
    return value if math.isfinite(value) else None


def _clamp_fraction(value: Any) -> float:
    v = _n(value)
    return 0 if v is None else min(1, max(0, v))


def _bounded(value: Any, lo: float, hi: float) -> float | int | None:
    v = _n(value)
    return v if v is not None and lo <= v <= hi else None


def _sanitize_growth_value(raw: Any, industry: Any) -> tuple[float | None, bool]:
    v = _n(raw)
    if v is None:
        return None, False
    bound = (
        SUSPECT_REV_GROWTH_FINANCIAL
        if is_financial_industry(industry)
        else SUSPECT_REV_GROWTH_GENERAL
    )
    return (None, True) if v < -100 or v > bound else (v, False)


def sanitize_revenue_growth(row: Mapping[str, Any]) -> tuple[float | None, bool]:
    return _sanitize_growth_value(row.get("revenueGrowthTTM"), row.get("industry"))


def sanitize_quarterly_rev_growth(row: Mapping[str, Any]) -> tuple[float | None, bool]:
    return _sanitize_growth_value(row.get("revenueGrowthQuarterly"), row.get("industry"))


def sanitize_score_row(row: Mapping[str, Any]) -> dict[str, Any]:
    out = dict(row)
    out["marketCap"] = _bounded(row.get("marketCap"), _JS_MIN_VALUE, _JS_MAX_VALUE)
    out["currentPrice"] = _bounded(row.get("currentPrice"), _JS_MIN_VALUE, _JS_MAX_VALUE)
    out["trailingPE"] = _bounded(row.get("trailingPE"), _JS_MIN_VALUE, 1_000)
    out["forwardPE"] = _bounded(row.get("forwardPE"), _JS_MIN_VALUE, 1_000)
    out["dividendYieldPercent"] = _bounded(row.get("dividendYieldPercent"), 0, 25)
    out["ytdReturn"] = _bounded(row.get("ytdReturn"), -100, 1_000)
    out["fcfYieldPercent"] = _bounded(row.get("fcfYieldPercent"), -100, 100)
    out["revenueGrowthTTM"] = sanitize_revenue_growth(row)[0]
    out["revenueGrowthQuarterly"] = sanitize_quarterly_rev_growth(row)[0]
    out["evToEbitda"] = _bounded(row.get("evToEbitda"), _JS_MIN_VALUE, 1_000)
    out["interestCoverage"] = _bounded(row.get("interestCoverage"), -10_000, 10_000)
    out["operatingMarginTTM"] = _bounded(row.get("operatingMarginTTM"), -200, 100)
    out["operatingMargin5Y"] = _bounded(row.get("operatingMargin5Y"), -200, 100)
    out["rangePosition"] = _bounded(row.get("rangePosition"), 0, 1)
    return out


def compute_breakdown(input_row: Mapping[str, Any]) -> dict[str, int]:
    row = sanitize_score_row(input_row)
    pe = _n(row.get("trailingPE"))
    fwd_pe = _n(row.get("forwardPE"))
    fcf = _n(row.get("fcfYieldPercent"))
    rev_growth = sanitize_revenue_growth(row)[0]
    de = _n(row.get("debtToEquity"))
    ev_ebitda = _n(row.get("evToEbitda"))
    div_yield = _n(row.get("dividendYieldPercent"))
    ytd = _n(row.get("ytdReturn"))
    range_pos = (
        _n(_clamp_fraction(row.get("rangePosition")))
        if row.get("rangePosition") is not None
        else None
    )

    financial = is_balance_sheet_financial(row.get("ticker"), row.get("industry"))

    earnings_quality = 0
    if not financial:
        if fcf is not None and fcf < 0:
            earnings_quality = -1
        elif fcf is not None and pe is not None and pe > 0:
            conversion = (fcf * pe) / 100
            earnings_quality = (
                1 if conversion > EQ_CONVERSION_STRONG
                else -1 if conversion < EQ_CONVERSION_WEAK
                else 0
            )

    leverage = 0
    if de is not None and not financial and not is_reit_industry(row.get("industry")):
        ic = _n(row.get("interestCoverage"))
        if ic is not None and ic < WEAK_INTEREST_COVERAGE:
            leverage = -1
        elif 0 <= de <= EXTREME_DE_RATIO:
            leverage = 1 if de < 1.0 else -1 if de > 2.0 else 0

    revenue_growth = (
        (1 if rev_growth > 10 else -1 if rev_growth < 0 else 0)
        if rev_growth is not None
        else 0
    )

    rev_q = sanitize_quarterly_rev_growth(row)[0]
    revenue_acceleration = 0
    if rev_growth is not None and rev_q is not None:
        revenue_acceleration = (
            1 if rev_q > rev_growth + REV_ACCEL_THRESHOLD_PP
            else -1 if rev_q < rev_growth - REV_ACCEL_THRESHOLD_PP
            else 0
        )

    fcf_yield_level = (
        (1 if fcf > 5 else -1 if fcf < 2 else 0)
        if fcf is not None and not financial
        else 0
    )

    op_ttm = _n(row.get("operatingMarginTTM"))
    op_5y = _n(row.get("operatingMargin5Y"))
    margin_inflection = 0
    if op_ttm is not None and op_5y is not None:
        margin_inflection = (
            1 if op_ttm > op_5y + MARGIN_INFLECTION_PP
            else -1 if op_ttm < op_5y - MARGIN_INFLECTION_PP
            else 0
        )

    pe_compression = 0
    if pe is not None and fwd_pe is not None:
        pe_compression = 1 if fwd_pe < pe else -1 if fwd_pe > pe else 0
        if pe_compression == 1 and is_cyclical_industry(row.get("industry")):
            pe_compression = 0

    valuation = (
        (1 if ev_ebitda < 15 else -1 if ev_ebitda > 25 else 0)
        if ev_ebitda is not None and not financial
        else 0
    )

    dividend_coverage = 0
    if div_yield is not None and div_yield > 0 and not financial:
        if fcf is not None:
            dividend_coverage = 1 if fcf > div_yield else -1

    price_position = (
        (1 if range_pos < 0.4 else -1 if range_pos > 0.9 else 0)
        if range_pos is not None
        else 0
    )

    ytd_momentum = (1 if ytd > 0 else -1 if ytd < 0 else 0) if ytd is not None else 0

    dividend_yield = (
        (1 if div_yield > 1.5 else 0)
        if div_yield is not None and div_yield > 0
        else 0
    )

    return {
        "earningsQuality": earnings_quality,
        "leverage": leverage,
        "revenueGrowth": revenue_growth,
        "revenueAcceleration": revenue_acceleration,
        "fcfYieldLevel": fcf_yield_level,
        "marginInflection": margin_inflection,
        "peCompression": pe_compression,
        "valuation": valuation,
        "dividendCoverage": dividend_coverage,
        "pricePosition": price_position,
        "ytdMomentum": ytd_momentum,
        "dividendYield": dividend_yield,
    }


def compute_scores(breakdown: Mapping[str, int]) -> tuple[int, int]:
    strength = 0
    risk = 0
    for key in CRITERION_KEYS:
        weighted = breakdown[key] * CRITERION_WEIGHT[key]
        if weighted > 0:
            strength += weighted
        elif weighted < 0:
            risk += -weighted
    return strength, risk


def is_optically_cheap(row: Mapping[str, Any]) -> bool:
    if is_balance_sheet_financial(row.get("ticker"), row.get("industry")):
        return False
    ev = _n(row.get("evToEbitda"))
    fcf = _n(row.get("fcfYieldPercent"))
    return (ev is not None and ev < TRAP_CHEAP_EV_EBITDA) or (
        fcf is not None and fcf > TRAP_CHEAP_FCF_YIELD
    )


def is_value_trap(row: Mapping[str, Any]) -> bool:
    rev = sanitize_revenue_growth(row)[0]
    return rev is not None and rev < 0 and is_optically_cheap(row)


def is_peak_cycle(row: Mapping[str, Any]) -> bool:
    if not is_cyclical_industry(row.get("industry")):
        return False
    pe = _n(row.get("trailingPE"))
    fwd = _n(row.get("forwardPE"))
    return pe is not None and fwd is not None and fwd > pe and is_optically_cheap(row)


def compute_coverage(row: Mapping[str, Any]) -> dict[str, Any]:
    pe = _n(row.get("trailingPE"))
    fwd_pe = _n(row.get("forwardPE"))
    fcf = _n(row.get("fcfYieldPercent"))
    rev = sanitize_revenue_growth(row)[0]
    de = _n(row.get("debtToEquity"))
    ev_ebitda = _n(row.get("evToEbitda"))
    div_yield = _n(row.get("dividendYieldPercent"))
    ytd = _n(row.get("ytdReturn"))
    range_pos = (
        _n(_clamp_fraction(row.get("rangePosition")))
        if row.get("rangePosition") is not None
        else None
    )

    financial = is_balance_sheet_financial(row.get("ticker"), row.get("industry"))
    per_criterion = {
        "earningsQuality": (not financial, fcf is not None and (fcf < 0 or pe is not None)),
        "leverage": (not financial and not is_reit_industry(row.get("industry")), de is not None),
        "revenueGrowth": (True, rev is not None),
        "revenueAcceleration": (True, rev is not None and sanitize_quarterly_rev_growth(row)[0] is not None),
        "fcfYieldLevel": (not financial, fcf is not None),
        "marginInflection": (True, _n(row.get("operatingMarginTTM")) is not None and _n(row.get("operatingMargin5Y")) is not None),
        "peCompression": (True, pe is not None and fwd_pe is not None),
        "valuation": (not financial, ev_ebitda is not None),
        "dividendCoverage": (not financial, div_yield is not None and (div_yield <= 0 or fcf is not None)),
        "pricePosition": (True, range_pos is not None),
        "ytdMomentum": (True, ytd is not None),
        "dividendYield": (True, div_yield is not None),
    }

    covered = 0
    applicable = 0
    for key in CRITERION_KEYS:
        is_applicable, is_covered = per_criterion[key]
        if not is_applicable:
            continue
        applicable += 1
        if is_covered:
            covered += 1
    return {
        "covered": covered,
        "applicable": applicable,
        "fraction": 0 if applicable == 0 else covered / applicable,
    }


def has_insufficient_data(row: Mapping[str, Any], coverage: Mapping[str, Any] | None = None) -> bool:
    coverage = coverage if coverage is not None else compute_coverage(row)
    if coverage["fraction"] < MIN_CRITERION_COVERAGE:
        return True
    financial = is_balance_sheet_financial(row.get("ticker"), row.get("industry"))
    if not financial and _n(row.get("fcfYieldPercent")) is None:
        return True
    if (
        not financial
        and not is_reit_industry(row.get("industry"))
        and _n(row.get("debtToEquity")) is None
    ):
        return True
    return False


def is_benign_earnings_quality(row: Mapping[str, Any]) -> bool:
    fcf = _n(row.get("fcfYieldPercent"))
    rev = sanitize_revenue_growth(row)[0]
    return (
        fcf is not None and fcf >= BENIGN_EQ_MIN_FCF_YIELD
        and rev is not None and rev > BENIGN_EQ_MIN_REV_GROWTH
    )


def is_critical_earnings_quality(row: Mapping[str, Any]) -> bool:
    fcf = _n(row.get("fcfYieldPercent"))
    pe = _n(row.get("trailingPE"))
    if fcf is None:
        return False
    if fcf < 0:
        return True
    if pe is not None and pe > 0:
        return (fcf * pe) / 100 < EQ_CONVERSION_CRITICAL
    return False


def is_serviceable_leverage(row: Mapping[str, Any]) -> bool:
    ic = _n(row.get("interestCoverage"))
    return ic is not None and ic >= STRONG_INTEREST_COVERAGE


def is_disqualified(breakdown: Mapping[str, int], row: Mapping[str, Any]) -> bool:
    eq = (
        breakdown["earningsQuality"] == -1
        and is_critical_earnings_quality(row)
        and not is_benign_earnings_quality(row)
    )
    lev = breakdown["leverage"] == -1 and not is_serviceable_leverage(row)
    return eq or lev


def is_crowded(row: Mapping[str, Any]) -> bool:
    cap = _n(row.get("marketCap"))
    pos = _clamp_fraction(row.get("rangePosition")) if row.get("rangePosition") is not None else None
    return cap is not None and cap >= MEGA_CAP_THRESHOLD and pos is not None and pos > 0.9


def tier_for(strength_score: int, risk_score: int, flags: Mapping[str, bool]) -> str:
    if flags["disqualified"] or flags["insufficientData"] or risk_score >= RISK_FLOOR:
        return "weak"
    capped = flags["crowding"] or flags["valueTrap"] or flags["peakCycle"] or flags["softEarningsQuality"]
    if strength_score >= 12:
        return "moderate" if capped else "strong"
    if strength_score >= 7:
        return "moderate"
    return "weak"


def score_row(raw_row: Mapping[str, Any]) -> dict[str, Any]:
    """Score one row; returns the golden-fixture output shape (sans row echo)."""
    row = sanitize_score_row(raw_row)
    breakdown = compute_breakdown(row)
    strength, risk = compute_scores(breakdown)
    coverage = compute_coverage(row)
    flags = {
        "disqualified": is_disqualified(breakdown, row),
        "cyclical": is_cyclical_industry(row.get("industry")),
        "crowding": is_crowded(row),
        "benignEarningsQuality": breakdown["earningsQuality"] == -1 and is_benign_earnings_quality(row),
        # Deliberately reads the RAW row: sanitize already nulled suspect values.
        "suspectRevenueGrowth": sanitize_revenue_growth(raw_row)[1] or sanitize_quarterly_rev_growth(raw_row)[1],
        "insufficientData": has_insufficient_data(row, coverage),
        "valueTrap": is_value_trap(row),
        "peakCycle": is_peak_cycle(row),
        "serviceableLeverage": breakdown["leverage"] == -1 and is_serviceable_leverage(row),
        "softEarningsQuality": (
            breakdown["earningsQuality"] == -1
            and not is_critical_earnings_quality(row)
            and not is_benign_earnings_quality(row)
        ),
    }
    return {
        "breakdown": breakdown,
        "strengthScore": strength,
        "riskScore": risk,
        "coverage": coverage,
        "flags": flags,
        "tier": tier_for(strength, risk, flags),
    }
